### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by ai2010** [asaparov/parser#1]
Compiling the parser I got the following errors:

`parser.cpp:896:68:   required from here
./grammar/parser.h:2504:9: error: ‘log_probability’ is not a member template function
make: *** [parser.release.o] Error 1`

How can I solve that?

**Comment by asaparov** [comment]
Hmm, what compiler and which version are you using? What is your OS? My guess is that this is a compiler bug that existed in very old versions of g++ and clang, but has since been fixed.
